DROP TABLE IF EXISTS users cascade;

CREATE TABLE users(
     id SERIAL PRIMARY KEY,
     first VARCHAR NOT NULL,
     last VARCHAR NOT NULL,
     email VARCHAR UNIQUE NOT NULL,
     hashed_password VARCHAR NOT NULL,
     img_url TEXT,
     bio TEXT,
     timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
 ); 

 DROP TABLE IF EXISTS reset_codes;

  CREATE TABLE reset_codes(
    id SERIAL PRIMARY KEY,
    email VARCHAR NOT NULL REFERENCES users (email) ON DELETE CASCADE,
    code VARCHAR NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

DROP TABLE IF EXISTS friendships;

   CREATE TABLE friendships(
   id SERIAL PRIMARY KEY,
   sender_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   recipient_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   accepted BOOLEAN DEFAULT false
);

DROP TABLE IF EXISTS messages; 

   CREATE TABLE messages(
   id SERIAL PRIMARY KEY,
   text TEXT,
   user_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS wallposts; 

   CREATE TABLE wallposts(
   id SERIAL PRIMARY KEY,
   sender_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   recipient_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   text TEXT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS connected; 

   CREATE TABLE connected(
   id SERIAL PRIMARY KEY,
   connected_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
   socket TEXT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

